### ISSUE TITLE
Re-direction of Garima Girls Project Page (Gitbook link changed)

### ISSUE THREAD

**Issue by ssndu** [janastu/blog.janastu.org#10] opened 2021-02-10 12:50 UTC
Old URL: https://open.janastu.org/our-work/projects/garmi-girls-project

New URL: https://open.janastu.org/our-work/projects/mxpr-girls

Fix broken links to the page if any....

**Comment by salus-sage** [comment] 2021-02-11 10:48
wrong repo.
The issue is fixed, broken links are auto fixed in open.janastu.org

**Closed by salus-sage** 2021-02-11 10:48 UTC
